language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
  - export TZ='Asia/Shanghai'
  - chmod +x mvnw

script:
  - mvn clean compile

after_success:
  - bash <(curl -s https://codecov.io/bash)