spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/information_schema?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      #      ddl-auto: create-drop
      ddl-auto: none
    show-sql: true