#############################################################################
# Spring Boot Logging
#############################################################################

logging:
  level:
    root: DEBUG
  file: server.log

#############################################################################
# Spring Boot Management
#############################################################################

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: auditevents, env, httptrace, info, health, logfile

#############################################################################
# Spring Boot Server
#############################################################################

server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  tomcat:
    basedir: .
    max-connections: 200
    min-spare-threads: 4
    max-threads: 8
    resource:
      cache-ttl: 60000

#############################################################################
# Spring Boot JavaMelody
#############################################################################

javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  # excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests:
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    http-transform-pattern: \d+
    # to add basic auth:
    authorized-users: admin:admin
    # to change the default storage directory:
    storage-directory: /tmp/javamelody/freemarker-demo
    # to change the default "/monitoring" path:
    monitoring-path: /admin/monitoring

#############################################################################
# Spring Boot FreeMarker Demo
#############################################################################

my:
  server:
    resttemplate:
      connect-timeout: 2000
      read-timeout: 20000
    page:
      static:
        cache-ttl: 10000
